---
ID: "b6a99165-e79a-5309-a11d-d422cc0192a6"
Parent: "bcc282bf-8dc7-51e6-8b3d-6c704aa9705d"
Template: "bcc282bf-8dc7-51e6-8b3d-6c704aa9705d"
Path: "/sitecore/templates/Project/basicnextjsdemo/Styleguide-FieldUsage-ItemLink/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210920T214802Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ebf4de5e-f41a-422d-877a-06e7606c8133"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210920T214802Z
