---
ID: "b0e404a4-fc62-562b-876e-9cea82b2b64c"
Parent: "1f715c43-bf17-5ae5-9d7f-dba00e37f1bc"
Template: "1f715c43-bf17-5ae5-9d7f-dba00e37f1bc"
Path: "/sitecore/templates/Project/basicnextjsdemo/Styleguide-Section/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210920T214809Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "cd68c8d7-3f9d-4d63-8ec8-c8e35a3787a6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210920T214809Z
