---
ID: "46a1650a-884a-5778-921f-f2ef6b7593f1"
Parent: "776b65dd-e507-5fa9-a04a-e6f0e8934c2e"
Template: "776b65dd-e507-5fa9-a04a-e6f0e8934c2e"
Path: "/sitecore/templates/Project/basicnextjsdemo/Styleguide-FieldUsage-Number/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210920T214804Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e3698e34-a3de-4db6-b3bb-45b73cf60973"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210920T214804Z
