---
ID: "1ce37bae-86c6-5754-ae65-e5f8eab3d0bf"
Parent: "7131a997-a3fc-50c3-9b80-91d1b1f3c2bb"
Template: "7131a997-a3fc-50c3-9b80-91d1b1f3c2bb"
Path: "/sitecore/templates/Project/basicnextjsdemo/Styleguide-Tracking/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210920T214812Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6b1a5d30-dcac-4ac5-8df9-744fe1a98d27"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210920T214812Z
