---
ID: "bd7cd7b5-3778-5a15-8b76-fdf0ba8f54f9"
Parent: "dacab5a4-a629-5310-9a0a-639b3df42b22"
Template: "dacab5a4-a629-5310-9a0a-639b3df42b22"
Path: "/sitecore/templates/Project/basicnextjsdemo/Styleguide-Layout-Reuse/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210920T214807Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a3c72966-34f9-4f25-a168-dbd6186220b1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210920T214807Z
